'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.1
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SiriProx.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1328473249_246() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1328473249_246", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1328635139_monotone_close_exit_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1328635139_monotone_close_exit_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DiffieHellman() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DiffieHellman", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property hidemenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hidemenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hidemenu_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hidemenu_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property installed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("installed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ionic_Zip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ionic_Zip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        '''</summary>
        Friend ReadOnly Property IP() As String
            Get
                Return ResourceManager.GetString("IP", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property maximize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maximize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maximize_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maximize_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maximize_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maximize_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MobileDevice() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MobileDevice", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property MySql_Data() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MySql_Data", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Org_Mentalis_Security() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Org_Mentalis_Security", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seperator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seperator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tamir_SharpSSH() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Tamir_SharpSSH", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Top2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Top2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uninstall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uninstall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
